MODULE = gnrc_aodvv2
include $(RIOTBASE)/Makefile.base
INCLUDES += -I$(RIOTBASE)/sys/include/net/gnrc/aodvv2
INCLUDES += -I$(RIOTBASE)/sys/include
INCLUDES += -I$(RIOTBASE)/sys/include/net
INCLUDES += -I$(RIOTBASE)/sys/posix/include
